// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfpks51lr2AU9X5hQ4Vnk3ioaD6HcmGbI',
    appId: '1:403271012404:web:0019b3f69fbc6af46eba61',
    messagingSenderId: '403271012404',
    projectId: 'prueba2-730a7',
    authDomain: 'prueba2-730a7.firebaseapp.com',
    databaseURL: 'https://prueba2-730a7-default-rtdb.firebaseio.com',
    storageBucket: 'prueba2-730a7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMkY5vhC0v6pyZuIU7w8XuOHSPH7PmbpE',
    appId: '1:403271012404:android:b1337a23ba93678c6eba61',
    messagingSenderId: '403271012404',
    projectId: 'prueba2-730a7',
    databaseURL: 'https://prueba2-730a7-default-rtdb.firebaseio.com',
    storageBucket: 'prueba2-730a7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaeTLLnsWpp8GKJbO12PhT8Yer8NgFOLE',
    appId: '1:403271012404:ios:1c1a08e3694b90c86eba61',
    messagingSenderId: '403271012404',
    projectId: 'prueba2-730a7',
    databaseURL: 'https://prueba2-730a7-default-rtdb.firebaseio.com',
    storageBucket: 'prueba2-730a7.firebasestorage.app',
    iosBundleId: 'com.example.prueba2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaeTLLnsWpp8GKJbO12PhT8Yer8NgFOLE',
    appId: '1:403271012404:ios:1c1a08e3694b90c86eba61',
    messagingSenderId: '403271012404',
    projectId: 'prueba2-730a7',
    databaseURL: 'https://prueba2-730a7-default-rtdb.firebaseio.com',
    storageBucket: 'prueba2-730a7.firebasestorage.app',
    iosBundleId: 'com.example.prueba2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfpks51lr2AU9X5hQ4Vnk3ioaD6HcmGbI',
    appId: '1:403271012404:web:2da245af30ef1a056eba61',
    messagingSenderId: '403271012404',
    projectId: 'prueba2-730a7',
    authDomain: 'prueba2-730a7.firebaseapp.com',
    databaseURL: 'https://prueba2-730a7-default-rtdb.firebaseio.com',
    storageBucket: 'prueba2-730a7.firebasestorage.app',
  );

}